#!/usr/bin/env tsx
// Walks packages/db/src/schema.ts at the TypeScript level and emits row
// types (`User`, `NewUser`, …) to packages/db/src/generated/types.ts.
//
// Deterministic, idempotent. Run after editing schema.ts:
//   pnpm db:codegen
// CI runs this and `git diff --exit-code` to catch stale generated files.
//
// We don't introspect a live DB here — that's a separate concern. Schema
// drift between TS and migrations is caught by `drizzle-kit check` at
// migration-generate time.

import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { PgTable } from 'drizzle-orm/pg-core';

// tsx (the runtime) accepts importing TS files without a .js suffix;
// the `.js` form keeps tsc --noEmit happy (`allowImportingTsExtensions`
// isn't on) and matches the bundler-resolution convention.
import * as schema from '../src/schema.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(__dirname, '../src/generated/types.ts');

const tables = Object.entries(schema)
  .filter(([, value]) => value instanceof PgTable)
  .sort(([a], [b]) => a.localeCompare(b));

if (tables.length === 0) {
  throw new Error('codegen found no pgTable exports in schema.ts');
}

// camelCase plural → PascalCase singular: `users` → `User`,
// `authSessions` → `AuthSession`, `learningLinks` → `LearningLink`.
function pascalSingular(name: string): string {
  const pascal = name.charAt(0).toUpperCase() + name.slice(1);
  return pascal.endsWith('s') ? pascal.slice(0, -1) : pascal;
}

const header = `// Auto-generated by packages/db/scripts/codegen.ts. Do not edit.
// Run \`pnpm db:codegen\` after any change to packages/db/src/schema.ts.

import type { InferInsertModel, InferSelectModel } from 'drizzle-orm';

import type * as schema from '../schema.js';
`;

const body = tables
  .map(([key]) => {
    const T = pascalSingular(key);
    return `
export type ${T} = InferSelectModel<typeof schema.${key}>;
export type New${T} = InferInsertModel<typeof schema.${key}>;`;
  })
  .join('\n');

writeFileSync(OUT, header + body + '\n');
process.stdout.write(`Wrote ${tables.length} table type pairs → ${OUT}\n`);
